name: INharmonics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74763
title: Game Audio Crafter - for all your Game Audio needs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#63c0e2'
    - '#a7839f'
    - '#ffffff'
    - '#b3b3cc'
    - '#8080ff'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
